services:
  - type: web
    name: bizscanner
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: DATABASE_URL
        fromDatabase:
          name: bizscanner
          property: connectionString

databases:
  - name: bizscanner
    plan: free
